name: demo_server
description: Demonstration Web server for woomera_server_gen example
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.4.2
  logging: ^1.2.0
  woomera: ^8.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  woomera_server_gen:
    path: ../..
