name: woomera_server_gen
description: Generates woomera server Dart code from woomera annotations.
version: 0.0.2
repository: https://github.com/hoylen/woomera_server_gen

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.2.0
  woomera: ^8.0.1

dev_dependencies:
  args: ^2.4.2
  lints: '>=2.0.0 <=4.0.0'
  test: ^1.21.0
  pana: ^0.21.37
